###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/10c8c216-9244-466f-8472-a1229a12aaa4

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Danilo José Marins",
    "email": "danilojmarins@hotmail.com",
    "password": "12345678"
}

###
GET http://localhost:3000/users/04fcd43e-d983-4c83-9a1c-2218090a7041

###
PATCH http://localhost:3000/users/04fcd43e-d983-4c83-9a1c-2218090a7041
Content-Type: application/json

{
    "name": "Danilo José Marins",
    "email": "danilojmarins@hotmail.com",
    "password": "12345678"
}

###
DELETE http://localhost:3000/users/d8abb49f-1b8f-4296-974d-69373cea44fd

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "danilojmarins@hotmail.com",
    "password": "12345678"
}

###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0ZmNkNDNlLWQ5ODMtNGM4My05YTFjLTIyMTgwOTBhNzA0MSIsIm5hbWUiOiJEYW5pbG8gSm9zw6kgTWFyaW5zIiwiaWF0IjoxNzA4MDUyNzA3LCJleHAiOjE3MDgxMzkxMDd9.tN8hqlWRXjvoSFVdWuEDQ2vFJ82ey6-_H1X1vSrzgiU

###
GET http://localhost:3000/orders/adsad
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0ZmNkNDNlLWQ5ODMtNGM4My05YTFjLTIyMTgwOTBhNzA0MSIsIm5hbWUiOiJEYW5pbG8gSm9zw6kgTWFyaW5zIiwiaWF0IjoxNzA4MDUyNzA3LCJleHAiOjE3MDgxMzkxMDd9.tN8hqlWRXjvoSFVdWuEDQ2vFJ82ey6-_H1X1vSrzgiU

###
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0ZmNkNDNlLWQ5ODMtNGM4My05YTFjLTIyMTgwOTBhNzA0MSIsIm5hbWUiOiJEYW5pbG8gSm9zw6kgTWFyaW5zIiwiaWF0IjoxNzA4MDUyNzA3LCJleHAiOjE3MDgxMzkxMDd9.tN8hqlWRXjvoSFVdWuEDQ2vFJ82ey6-_H1X1vSrzgiU

{
    "card_hash": "e07e4052-047d-4031-ab13-a12604f804e7",
    "items": [
        {
            "product_id": "10c8c216-9244-466f-8472-a1229a12aaa4",
            "quantity": 2
        },
        {
            "product_id": "414789db-2874-4f4c-b4a1-4951490fb480",
            "quantity": 1
        }
    ]
}