POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Processadores"
}

###

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/category/384aef94-8817-4609-8ded-f3edcc02859d HTTP/1.1
Host: localhost:8080
Content-Type: application/json


### Products

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Intel i7 10700",
    "description": "Processador Intel i7 10700 2.5GHz",
    "price": 1599.99,
    "category_id": "384aef94-8817-4609-8ded-f3edcc02859d",
    "image_url": "URL/teste"
}

###

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/19c1641d-5bed-4053-8309-4c24945fe349 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/category/384aef94-8817-4609-8ded-f3edcc02859d HTTP/1.1
Host: localhost:8080
Content-Type: application/json